export const CHANGECURRENTSONG = 'changeCurrentSong'
export const ADDSONGPAGEMES = 'addSongPageMes'
export const CLEARSONGPAGEMES = 'clearSongPageMes'
export const CHANGESONGLIST = 'changeSongList'
export const CHANGECURRENTSONGINDEX = 'changCurrentSongIndex'